name: "e2g-run-case-file-action"
description: "Runs a case file"
author: "The Equity Engineering Group"
inputs:
  calc-dir:
    required: true
    description: "path to a calculator src directory that contains an examples.js"
  static-dir:
    required: true
    description: "path to the static dir where the example files are stored"
  base-url:
    description: "the bare base url for the instance to submit the job to"
    default: "dev.e2g.com"
  auth-secret:
    description: "the auth secret"
    required: true
  timeout:
    description: "timeout in seconds"
    default: "1800"
runs:
  using: "node16"
  main: "dist/index.js"
  pre: "dist/pre/index.js"
